all:
  vars:
    ansible_user: p2ops
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_p2homeos"
    ansible_ssh_common_args: "-o BatchMode=yes -o StrictHostKeyChecking=yes"

  children:
    control_nodes:
      hosts:
        core-01:
          ansible_connection: local
          ansible_host: 127.0.0.1
          node_role: control-plane

    compute_nodes:
      hosts:
        compute-01:
          ansible_host: 192.168.0.31
          production_ip: 192.168.0.31
          node_role: primary-compute
          osho_role: autopilot-primary
        compute-02:
          ansible_host: 192.168.0.88
          production_ip: 192.168.0.88
          node_role: orchestration
          osho_role: dashboard-controller
        compute-03:
          ansible_host: 192.168.0.158
          production_ip: 192.168.0.158
          node_role: gpu-worker
          osho_role: worker
        compute-04:
          ansible_host: 192.168.0.177
          production_ip: 192.168.0.177
          node_role: light-gpu-worker
          osho_role: standby
        media-01:
          ansible_host: 192.168.0.6
          production_ip: 192.168.0.6
          node_role: media-processing

    network_switches:
      hosts:
        switch-02:
          ansible_host: 192.168.0.65
          ansible_user: psquare
          ansible_connection: ansible.netcommon.netconf
          ansible_network_os: junipernetworks.junos.junos
          node_role: access-switch
          switch_model: ex2300-c-12p

    power_controllers:
      hosts:
        p2-g50-01:
          ansible_host: 192.168.0.236
          ansible_connection: local
          node_role: rack-power-primary
          power_model: APC-G50NETB2
          mac_address: 28:29:86:19:72:b8
          management_state: p2-managed
        p2-g50-02:
          ansible_host: 192.168.0.240
          ansible_connection: local
          node_role: rack-power-secondary
          power_model: APC-G50NETB2
          mac_address: 28:29:86:19:72:bc
          management_state: p2-managed

    gpu_nodes:
      hosts:
        compute-01:
        compute-03:
        compute-04:
        media-01:

    media_nodes:
      hosts:
        media-01:

    osho_nodes:
      hosts:
        compute-01:
        compute-02:
        compute-03:
